export const ADD_POSTS_START = "ADD_POSTS_START";
export const ADD_POSTS_SUCCESS = "ADD_POSTS_SUCCESS";
export const ADD_POSTS_FAILED = "ADD_POSTS_FAILED";

export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";

export const NEW_USER_SIGN_UP_START = "NEW_USER_SIGN_UP_START";
export const NEW_USER_SIGN_UP_SUCCESS = "NEW_USER_SIGN_UP_SUCCESS";
export const NEW_USER_SIGN_UP_FAILED = "NEW_USER_SIGN_UP_FAILED";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
