export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const ADD_POSTS_START = "ADD_POSTS_START";
export const ADD_POSTS_SUCCESS = "ADD_POSTS_SUCCESS";
export const ADD_POSTS_FAIL = "ADD_POSTS_FAIL";
