export const ADD_POST_START = "ADD_POST_START";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILED = "ADD_POST_FAILED";

export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";

export const NEW_USER_SIGN_UP_START = "NEW_USER_SIGN_UP_START";
export const NEW_USER_SIGN_UP_SUCCESS = "NEW_USER_SIGN_UP_SUCCESS";
export const NEW_USER_SIGN_UP_FAILED = "NEW_USER_SIGN_UP_FAILED";

export const FETCH_USER_DATA_START = "FETCH_USER_DATA_START";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILED = "FETCH_USER_DATA_FAILED";

export const ADD_USER_POST_START = "ADD_USER_POST_START";
export const ADD_USER_POST_SUCCESS = "ADD_USER_POST_SUCCESS";
export const ADD_USER_POST_FAILED = "ADD_USER_POST_FAILED";

export const FETCH_USER_POSTS_START = "FETCH_USER_POSTS_START";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_FAILED = "FETCH_USER_POSTS_FAILED";
